### ISSUE TITLE
Finish classes (mostly done)

### ISSUE THREAD

**Issue by reaganmcf** [nakala-lang/nakala#11]
Classes are mostly done, but I have hit a big wall with property accesses. Every implementation that I can think of at the moment is not very elegant and leaves me with a sour taste in my mouth. So, for now, you can create and initialize classes but cannot call the defined functions or anything.

For example, the following works and will be interpreted correctly:
```
class Apple {
    fields { weight }

    fn get_weight() {
         weight
    }
}

let x = new Apple(104.3)
```

But property accesses and function calls on class methods are not built into the parser at all. Example:
```
x.weight

x.get_weight()
```

It would be really cool to have this kind of feature, especially with how close to being done classes are. I might work on it later but I'm going to have to think of an interesting way to tackle the problem.

**Comment by arzg** [comment]
When in doubt I like to look at [how rust-analyzer handles things](https://github.com/rust-analyzer/rust-analyzer/blob/3dae94bf2b3e496adb049da589c7efef272a39b8/crates/parser/src/grammar/expressions.rs#L378). Here is roughly what you could do:

```rust
fn expr_binding_power(p: &mut Parser, minimum_binding_power: u8) -> Option<CompletedMarker> {
    let mut lhs = lhs()?;

    while p.at(TokenKind::Dot) {
        let m = lhs.precede(p);
        p.bump();
        p.expect(TokenKind::Ident);
        lhs = m.complete(p, SyntaxKind::FieldExpr);
    }

    loop {
        // same as before
    }

    Some(lhs)
}
```

This automatically accesses `foo` on `bar` in `baz + bar.foo`, while accessing `foo` on the entire expression in `(baz + bar).foo`.

**Comment by reaganmcf** [comment]
Closing since language has been almost entirely rewritten
